name: Deploy inreach parser

on:
  push:
    branches: ['master', 'dev', 'feat/az-function']
    paths: ['inreach-parser/**', '.github/workflows/inreach-parser.yaml']
  pull_request:

env:
  FUNCTION_APP_NAME: bikejamboree-inreach-parser # Name of the function
  PACKAGE_PATH: ./inreach-parser # Applciation path in repository
  RESOURCE_GROUP_NAME: zhp-bikejamboree

jobs:
  deploy:
    name: Deploy to Azure Functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Validate Bicep
        id: bicep-validate
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: '35e22786-93ea-47c8-902a-16e9d0f03e17'
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./inreach-parser/inreach-parser.bicep
          deploymentMode: Validate

      - name: Deploy Bicep
        id: bicep-deploy
        uses: azure/arm-deploy@v1
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        with:
          subscriptionId: '35e22786-93ea-47c8-902a-16e9d0f03e17'
          resourceGroupName: ${{ env.RESOURCE_GROUP_NAME }}
          template: ./inreach-parser/inreach-parser.bicep
          deploymentMode: Incremental

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependiences
        run: npm ci
        working-directory: ./inreach-parser

      - name: Deploy function code
        uses: azure/functions-action@v1
        if: ${{ success() && github.ref == 'refs/heads/master' }}
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: ${{ env.PACKAGE_PATH }}
